### PR TITLE
run tests

### PR DESCRIPTION
**Pull request by sdarwin**
Don't merge.  Trigger existing ci tests, without other changes, checking the build status.

### CODE REVIEW

**Comment by sdarwin** [comment]
The test demonstrates that .azure-pipelines.yml will probably need to be updated.  ok. 

Also another interesting result, one target on msvc-14.2 has been consistently failing. This isn't "random", same result last week.   

@vinniefalco any idea?

https://github.com/CPPAlliance/url/runs/4287984429?check_suite_focus=true

```
compile-c-c++ bin.v2\libs\url\test\unit\segments_encoded_view.test\msvc-14.2\debug\address-model-32\cxxstd-20-iso\threading-multi\segments_encoded_view.obj
segments_encoded_view.cpp
msvc.link bin.v2\libs\url\test\unit\segments_encoded_view.test\msvc-14.2\debug\address-model-32\cxxstd-20-iso\threading-multi\segments_encoded_view.exe
testing.capture-output bin.v2\libs\url\test\unit\segments_encoded_view.test\msvc-14.2\debug\address-model-32\cxxstd-20-iso\threading-multi\segments_encoded_view.run
====== BEGIN OUTPUT ======
boost.url.segments_encoded_view
#51 segments_encoded_view.cpp(86) failed: v0 == v1
```

**Comment by vinniefalco** [comment]
No idea about that failing test.

**Comment by vinniefalco** [comment]
@alandefreitas want to look into the msvc test failure?

**Comment by alandefreitas** [comment]
> @alandefreitas want to look into the msvc test failure?

Sure 👍

**Comment by vinniefalco** [comment]
So...what is the status of this?

**Comment by alandefreitas** [comment]
> So...what is the status of this?

We identified and fixed the problem a couple of weeks ago: `segments_encoded::iterator::operator*` should have been returning a `reference`, which is a `string_view`, because of how C++20 defines `iterator_traits::reference`.

For instance, [these tests](https://github.com/CPPAlliance/url/pull/87), which are more recent, didn't fail for "CI / windows (msvc-14.2, 14,17,20, 32,64, windows-2019) (pull_request)". I think the results above are just old.

Anyway, the problem was difficult to identify but quite easy to fix. Less than 10 `char`s. 🙂 If I'm wrong about this and this is not fixed yet, I can open a PR.

**Pull request closed without merging**
