### PR TITLE
implement basic_url value semantics

### PR DESCRIPTION
**Pull request by AlexandreBossard**
This pull request proposes an implementation of copy/assignment/swap operators for basic_url.

### CODE REVIEW

**Comment by vinniefalco** [comment]
This project is still being developed and not really ready for any contributions. If you will note, I have pushed a new implementation which uses `json::storage_ptr` which is preferred over _Allocator_.

**Comment by AlexandreBossard** [comment]
I did note that :D. As it is, this library is more useful and suitable to my use case than anything else I found. The only thing is missing to me, is value semantics as per #36.

I'll close this for know and rebase and re-submit a new PR when I've got time.

**Comment by vinniefalco** [comment]
What makes it more useful? What specifically, so I know to make that part great

**Comment by AlexandreBossard** [comment]
I've used skyr-url until know, It has a lot of dependencies (like lt::expected, rangeV3, nlohmann::json and std::filesystem) that I don't need / are cumbersome. boost-url is just... boost that I already use for asio and beast. So boost-url is just smaller and easier to integrate into my project already.

Then I just need to extract the host (and port) from an url encoded string and the "target" (everything right of the first /) of the url. Not much more I would say.

**Pull request closed without merging**
