### PR TITLE
Add instructions to build the docs

### PR DESCRIPTION
**Pull request by sdarwin**
Scripts to build the documentation.

@zajo please try these and let me know if you run into any problems.

### CODE REVIEW

**Comment by vinniefalco** [comment]
@zajo did you try this?

**Comment by zajo** [comment]
Going to now.

**Comment by sdarwin** [comment]
- the scripts now detect if they are being run inside boost-root or not. Either configuration will be able to build the docs.
- the commit yesterday about 'XSLT import' fixes a build error.

**Comment by vinniefalco** [comment]
Don't those shell script files need a "git chmod +x" equivalent in order to be executed locally after fetching?

**Comment by sdarwin** [comment]
Git stores whether a file is executable or not. When checking out these files, it looks like they have permissions of 755, which means executable for the user.

```
-rwxr-xr-x 1 root root 2625 Mar 12 19:24 linuxdocs.sh
-rwxr-xr-x 1 root root 2718 Mar 12 19:24 osxdocs.sh
```

**Comment by vinniefalco** [comment]
Ah.... GitHub **used** to show you the file mode bits in the diff view, but it seems they moved it to be visible only under View File:
image

**Comment by sdarwin** [comment]
- added a Microsoft Windows version
- tested all operating system scripts (linux, osx, windows)

**Comment by vinniefalco** [comment]
Is this pull request still relevant or is it stale?

**Comment by sdarwin** [comment]
I believe this is still relevant and not stale.   

It "adds instructions to build the docs", which shouldn't affect too much or break CI. Could be merged.

**Comment by vinniefalco** [comment]
Yeah but that thing with the Windows script looks really try-hard. I just type "b2 doc" and it builds the docs.

**Comment by sdarwin** [comment]
> looks really try-hard. 

The script is assuming the user starts with nothing except the url repository.   Thus, it's
- installing saxon
- installing doxygen
- determining if the boost superproject is present.  If not, checking it out, copying the repo into the boost directory.
- building b2

It installs all dependencies, like a Drone job would. 

If you have those things set up in advance, you could skip using the script, and run "b2".

Or, not sure if you are specifically referring to the b2 command-line options. 

The b2 command-line options were based on earlier examples, going back to Travis CI.   If they can be removed, that's a good idea to simplify.

**Comment by sdarwin** [comment]
@vinniefalco wrote:
> I just type "b2 doc"

Set the scripts to run "b2 doc" without command-line flags.

**Pull request closed without merging**
