### PR TITLE
Fix preview docs build develop.url.cpp.al

### PR DESCRIPTION
**Pull request by sdarwin**
Let's check how this PR builds the docs and previews..

### CODE REVIEW

**Comment by sdarwin** [comment]
With this change, all previews seem to be rendering correctly.   

After the url library becomes an official repo, an option is to run "git revert", to "undo an existing commit", and return to the situation where the css file and other files are located in boost-root.

**Comment by vinniefalco** [comment]
There's a little glitch in the top right
image

**Comment by sdarwin** [comment]
> There's a little glitch in the top right

I see the screenshot, but don't immediately know which glitch you mean.    What is the issue, and does it appear on all the pages?

**Comment by vinniefalco** [comment]
There's a "Home Libraries People More" navigation which shouldn't be there - expand the window horizontally

**Comment by vinniefalco** [comment]
NuDB doesn't have it

**Comment by sdarwin** [comment]
This was already merge.  Closing PR.

**Pull request closed without merging**
